build:
    environment:
        php: '7.3.0'
            
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'

before_commands:
    - "composer install --prefer-source"
    
tools:
    php_code_coverage:
        test_command: vendor/bin/phpunit

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*