language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  
before_script:
  - composer self-update
  - composer --version
  - composer require sunra/php-simple-html-dom-parser --no-update

script: composer install --prefer-dist --no-interaction